_BASE_: "../Base-bagtricks.yml"

DATASETS:
  NAMES: ("LTCC",)
  TESTS: ("LTCC",)

OUTPUT_DIR: "logs/LTCC/bagtricks_R50"

MODEL:
  LOSSES:
    NAME: ("CrossEntropyLoss",)

    CE:
        EPSILON: 0.1
        SCALE: 1.

INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]


DATALOADER:
  PK_SAMPLER: False
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  IS_CLO_CHANGES: True

TEST:
  USE_ONLY_CLO: False

